name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths: "MiltonHistoricApp/**"
  pull_request:
    branches: [ master ]
    paths: "MiltonHistoricApp/**"

jobs:
  build_and_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      working-directory: ./MiltonHistoricApp
      run: npm ci
    
    - name: npm build
      working-directory: ./MiltonHistoricApp
      run: npm run build --if-present
      
    - name: npm test
      working-directory: ./MiltonHistoricApp
      run: npm test
  
  build_android:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./MiltonHistoricApp
        run: npm install
      - name: Build Android release
        working-directory: ./MiltonHistoricApp
        run: |
          cd android && ./gradlew bundleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app.aab
          path: MiltonHistoricApp/android/app/build/outputs/apk/release
        
        
