name: Continuous Integration

on:
  pull_request:
    branches: [ master ]
    paths: "MiltonHistoricApp/**"

jobs:
  test_pull_request:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: NPM CI
      working-directory: ./MiltonHistoricApp
      run: npm ci
      
    - name: npm test
      working-directory: ./MiltonHistoricApp
      run: npm test
        
